config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root "static_pages#home"
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  post '/email_processor' => 'griddler/emails#create'
end

app/models/email_processor.rb
class EmailProcessor
  def initialize(email)
    @email = email
  end

  def process

    user_name = @email.to[0][:token]
    user = User.find_by(mtname:user_name)

    if user
      sender_host_name = @email.from[:host]
      sender = Sender.find_by_name(sender_host_name) || Sender.create(name: sender_host_name, display_name: parse_display_name(sender_host_name) )
      Letter.create!({ content: @email.body, sender:sender, user:user, raw_html:@email.raw_html})
    end

  end

  def squash(name)
    name.downcase.gsub('.','').gsub(',','').gsub(' ','')
  end

  def parse_display_name(host_name)

    known_brands = ['Apple', 'General Assembly', 'J. Crew', 'Groupon', 'JetBlue', 'Kayak', 'Starbucks', 'Gilt', 'Travelocity', 'LivingSocial', 'CNET',
    'Smashing Magazine']
    known_brands.each do |brand|
      return brand if squash(host_name).include?(squash(brand))
    end

    if host_name.include? '.'
      return host_name.split('.')[0].capitalize
    end
    host_name
  end

end

app/models/letter.rb
class Letter < ActiveRecord::Base

  validates :user_id, presence: true
  validates :sender_id, presence: true
  default_scope -> {order('created_at DESC')}
  after_initialize :defaults

  belongs_to :sender
  belongs_to :user

  def defaults
    self.category ||= 'sale'
  end

end

app/models/sender.rb
class Sender < ActiveRecord::Base

  has_many :letters, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  before_save { self.email = email.downcase }
  before_save { self.mtname = mtname.downcase }
  before_create :create_remember_token

  has_many :letters, dependent: :destroy
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/letters_controller.rb
class  SendersController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  def index
    @senders = Sender.all
    @letters = Letter.all

    # RestClient.post "https://api:key-45353bea761148676ae6fbb927af15b5"\
    # "@api.mailgun.net/v2/sandbox471d5fcdac604d1baef1aac24fbe0849.mailgun.org/messages",
    # :from => "Mailgun Sandbox <postmaster@sandbox471d5fcdac604d1baef1aac24fbe0849.mailgun.org>",
    # :to => "Kyle Hogan <kylehogan1980@yahoo.com>",
    # :subject => "test2 fucker",
    # :text => "Congratulations Kyle Hogan, you just sent an email with Mailgun!  You are truly awesome!  You can see a record of this email in your logs: https://mailgun.com/cp/log .  You can send up to 300 emails/day from this sandbox server.  Next, you should add your own domain so you can send 10,000 emails/month for free."


  end

end

app/controllers/senders_controller.rb
class  SendersController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  def index
    @senders = Sender.all
    @letters = Letter.all

    # RestClient.post "https://api:key-45353bea761148676ae6fbb927af15b5"\
    # "@api.mailgun.net/v2/sandbox471d5fcdac604d1baef1aac24fbe0849.mailgun.org/messages",
    # :from => "Mailgun Sandbox <postmaster@sandbox471d5fcdac604d1baef1aac24fbe0849.mailgun.org>",
    # :to => "Kyle Hogan <kylehogan1980@yahoo.com>",
    # :subject => "test2 fucker",
    # :text => "Congratulations Kyle Hogan, you just sent an email with Mailgun!  You are truly awesome!  You can see a record of this email in your logs: https://mailgun.com/cp/log .  You can send up to 300 emails/day from this sandbox server.  Next, you should add your own domain so you can send 10,000 emails/month for free."


  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user

    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end

  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    redirect_to(user_path(current_user)) if current_user
    @user = User.new
    # binding.pry
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to MailTailor!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)

    @senders = @user.letters.map { |letter| letter.sender }.uniq
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :mtname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute( :remember_token, User.digest(User.new_remember_token) )
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MailTailor</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>
  <body>

<%= yield %>




    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/letters/index.html.erb
<h1>Look at all these mails!!</h1>
<br>

<% @letters.each do |letter| %>




  <% @letters.each do |letter|
    if letter.sender_id == sender.id %>

        <%=letter.content%>

      <br>
    <%end%>


    <%end%>

  <br>
<%end%>

app/views/senders/index.html.erb
<h1>Look at all these mails!!</h1>
<br>

<% @senders.each do |sender| %>

<%= sender.name %><br>
<%= sender.url %>

<%end%>

<% @senders.each do |sender| %>

  <h2><%= sender.name %></h2>
  <h3><%= sender.url %></h3>
  <% @letters.each do |letter|
    if letter.sender_id == sender.id %>
      <%=letter.content.html_safe%>
      <br>
    <%end%>
    <br>

    <%end%>
<%end%>
<hr>
<br><br><br><br><br><br>
<h1>And now just the mail!</h1>
<br><br>

<% @letters.each do |letter| %>
  <h4>letter</h4>
  <%=letter.content%>
  <%=letter.title%>
  <%=letter.id%>
  <br>
<% end %>

app/views/static_pages/home.html.erb
<div class = "container-fluid">

    <div class = "row page-header" id="header">
        <h1 class = "col-md-4 text-center">Mail Tailor</h1>
        <div class="col-md-2 col-md-offset-5">
                <a class="btn" role="button" id="create" data-toggle="modal" data-target="#createmodal">CREATE</a>
                <a class="btn" role="button" id="login" data-toggle="modal" data-target="#loginmodal">LOGIN</a>
        </div>
    </div>

    <div class= "row">
        <div class="modal fade" id="loginmodal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button><!-- the small little x that closes -->
                        <h4 class="modal-title text-center" id="myModalLabel">LOGIN</h4>
                    </div>
                    <div class="modal-body" id="modal-body">
                        <%= form_for(:session, url: sessions_path) do |f| %>

                            <%= f.label :email %>
                            <%= f.text_field :email %>

                            <%= f.label :password %>
                            <%= f.password_field :password %>

                            <%= f.submit("Sign in", :class => 'btn', :id => 'modallog' )%>
                        <% end %>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class= "row">
        <div class="modal fade" id="createmodal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title text-center" id="myModalLabel">CREATE</h4>
                    </div>



                    <div class="modal-body" id="modal-body">
                        <form action="/users" method="POST">
                            <label>Name <input id='name_input' name='user[name]' type='text' placeholder="name"></label>
                            <label>UserName <input name='user[mtname]' type='text' placeholder="username"></label>
                            <label>Email <input id='email_input' name='user[email]' type='text' placeholder="email"></label>
                            <label>Password <input id='password_input' name='user[password]' type='password' placeholder="password"></label>
                            <label>Confirm Password <input id='password_confirmation_input' name='user[password_confirmation]' type='password' placeholder="confirm password"></label>
                            <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
                            <button class="btn" id="modallog_create">CREATE</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div> <!-- closes container -->
<br>

<div class = "container">
    <div class="row">
      <div class = "col-md-3"></div>
      <div class = "col-md-6 col-xs-6">
        <img src= <%= asset_path('mailtailor_logo.png') %> alt="logo" id="logoHome"> </img>
        </div>
      <div class = "col-md-3"></div>
  </div>

app/views/users/dash.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="dashboardstyle.css">
<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="css/simple-sidebar.css" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <div class = "container-fluid">

     <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand" id="logo">
                    <a href="index.html">
                        MAIL THING
                    </a>
                </li>

                <li id="emailside">
                    EMAIL ADDRESS
                </li>

                <li>
                    <input placeholder="SEARCH" id="search">
                </li>

                <li>
                    <a href="#">AMAZON</a>
                </li>

            </ul>
        </div>
        <!-- /#sidebar-wrapper -->


        <!-- Page Content -->
          <div id="page-content-wrapper">
              <div class="container-fluid">
                  <div class="row">
                      <nav class="navbar navbar-default navbar-fixed-top" id="nav">
                          <div class="container-fluid">
                              <div class="navbar-header">
                                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                      <ul class="nav navbar-nav">
                                          <li><h3 id="sender">SENDER</h3></li>
                                          <li class="dropdown" id="dropdown">
                                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">MAIL TYPE <span class="caret"></span></a>
                                              <ul class="dropdown-menu" role="menu">
                                                  <li><a href="#">SALES</a></li>
                                                  <li class="divider"></li>
                                                  <li><a href="#">NEWS</a></li>
                                                  <li class="divider"></li>
                                                  <li><a href="#">ACCOUNT</a></li>
                                                  <li class="divider"></li>
                                              </ul>
                                          </li>
                                      </ul>
                                      <input type="text" placeholder="SEARCH" id="searchtop">
                                  </div><!-- /.navbar-collapse -->
                              </div><!-- /.container-fluid -->
                          </nav>
                          <% @user.letters.each do |letter| %>
                          <div class="col-lg-12" id="content">
                              <div id="email">
                                  <%= letter.title %> <br/>
                                  <br/>
                                  <%= letter.content.html_safe %>
                                  </div>

                          </div>

                      </div>
                  </div>
              </div><!-- /#page-content-wrapper -->
          </div> <!-- closes container -->
  <!-- Bootstrap JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  </body>
  </html>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>

  <%= f.label :mtname, 'Username' %> 
  <%= f.text_field :mtname %>@mailtailor.net
  <br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>

  <%= f.submit "Create my account" %>

<% end %>

app/views/users/show.html.erb
  <div class="container-fluid" style="background:grey">

     <div id="wrapper">

        <!-- Sidebar -->

        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand" id="logo"> MAIL TAILOR </li>
                <li> <input placeholder="SEARCH" id="search"> </li>
                <li> <span id="allSend">All Senders</span> </li>
                <% @senders.each do |sender| %>
                <li>
                      <span class="brands" id="<%= sender.display_name.gsub(" " , "").gsub('.' , "") %>"><%= sender.display_name %></span>
                      <button class= "delete" id="delete<%= sender.display_name.gsub(" " , "").gsub('.' , "") %>">DELETE</button>

                </li>
                <% end %>
                <li> <a class='btn btn-large' data-method='delete' href="<%= signout_path %>" >Log Out</a></li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->


        <!-- Page Content -->
          <div id="page-content-wrapper">
              <div class="container-fluid">
                  <div class="row">
                      <nav class="navbar navbar-default navbar-fixed-top" id="nav">
                          <div class="container-fluid">
                              <div class="navbar-header">
                                <div id="marqContainer">
                                  <h1 id="marquee">All Senders</h1>
                                </div>

                                <div id="catselect">
                                    <button id="noFilter">All</button>
                                    <button id="salesFilter">Sales</button>
                                    <button id="newsFilter">News</button>
                                    <button id="accountFilter">Account</button>
                                </div>
                              </div>
                              <!-- /.container-fluid -->
                          </nav>

                          <div id="mailDis">

                            <% @user.letters.each do |letter|%>
                                  <div class="col-lg-12 content">
                                      <div class = "email letterDiv class<%= letter.sender.display_name.gsub(" " , "").gsub('.' , "")%> <%= letter.category %>">
                                          <%= letter.title %> <button class="deleteSingle">Delete</button><br/>
                                          Received: <%= letter.created_at.strftime("%I:%M%p on %m/%d/%Y") %><br/>
                                          <%= letter.category %>
                                          <br/>

                                          <%= if letter.raw_html
                                              letter.raw_html.html_safe
                                            else
                                              letter.content
                                            end%>
                                      </div>

                                  </div>
                            <% end %>
                          </div>
                      </div>
                  </div>
              </div><!-- /#page-content-wrapper -->
          </div> <!-- closes container -->

  <script>
    var sendClassArray = [
      <% @senders.each do |sender| %>
        "class<%= sender.display_name.gsub(" " , "").gsub('.' , "") %>" ,
      <% end %>
    ]



    var mailDis = document.getElementById("mailDis");

    $( document ).ready(function() {

    $("#noFilter").click(function(){

                  $("#catselect").children().removeClass("changebackground");
                  $("#noFilter").addClass("changebackground");


                  $(".account").show();
                  $(".news").show();
                  $(".sale").show();
              });

    $("#salesFilter").click(function(){

            $("#salesFilter").addClass("changebackground");
            $("#noFilter").removeClass("changebackground");
            $("#newsFilter").removeClass("changebackground");
            $("#accountFilter").removeClass("changebackground");
            $(".sale").css( "display" , "block");
            $(".news").hide();
            $(".account").hide();

        });

    $("#newsFilter").click(function(){

            $("#newsFilter").addClass("changebackground");
            $("#noFilter").removeClass("changebackground");
            $("#salesFilter").removeClass("changebackground");
            $("#accountFilter").removeClass("changebackground");
            $(".news").show();
            $(".account").hide();
            $(".sale").hide();

        });

      $("#accountFilter").click(function(){

                    $("#accountFilter").addClass("changebackground");
                    $("#noFilter").removeClass("changebackground");
                    $("#salesFilter").removeClass("changebackground");
                    $("#newsFilter").removeClass("changebackground");
                    $(".account").show();
                    $(".news").hide();
                    $(".sale").hide();
                });



  <% @senders.each do |sender| %>

    var <%= 'get' + sender.display_name.gsub(" " , "").gsub("." , "") %> = document.getElementById("<%= sender.display_name.gsub(" " , "").gsub('.' , "") %>");


    $("#<%=sender.display_name.gsub(' ' , '').gsub('.' , '') %>").click(function(){

            $("#marquee").text('<%= sender.display_name %>');
            $("#mailDis").children().removeClass("showLetter").addClass("hideLetter");
            $("#<%=sender.display_name.gsub(' ' , '').gsub('.' , '') %>").parent().parent().children().removeClass("changebackground");
            $("#<%=sender.display_name.gsub(' ' , '').gsub('.' , '') %>").parent().toggleClass("changebackground");

            $(".class<%= sender.display_name.gsub(' ' , '').gsub('.' , '') %>").parent().removeClass("hideLetter");
            $(".class<%= sender.display_name.gsub(' ' , '').gsub('.' , '') %>").parent().addClass("showLetter");
        });






          $("#delete<%= sender.display_name.gsub(' ' , '').gsub('.' , '') %>").click(function() {
            var kill = window.confirm("are you sure you wish to delete?");
            if (kill == true){
              $("#<%=sender.display_name.gsub(' ' , '').gsub('.' , '') %>").parent().remove();
              $(".class<%= sender.display_name.gsub(' ' , '').gsub('.' , '') %>").remove();
            };
        });



  <% end %>

  $("#allSend").click(function(){
    $(this).parent().parent().children().removeClass("changebackground");
    $(this).parent().addClass("changebackground");
    $("#mailDis").children().addClass("showLetter");
    $("#marquee").text('All Senders');
  })

  $(".deleteSingle").click(function(){
    var killSingle = window.confirm("are you sure you wish to delete?");
    if (killSingle == true){
      $(this).parent().remove();
    };

  })

  $(".email").click(function(){
      console.log('clicked');
    $(this).toggleClass("fullSize");
  })
});

  </script>